name: Container on Kubernetes [CI]

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  BUILD:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ oi ${{ inputs.username }}"
      - run: printenv | sort
      
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ oi ${{ inputs.username }}"
      - run: printenv | sort      
      
